mqtt:
  sensor:
    - name: "Temperature Mock-1"
      state_topic: "home-assistant/mock-ds18b20/Mock-1"
      unit_of_measurement: "°C"
      availability: [{
          topic: "home-assistant/mock-ds18b20/availability",
          payload_available: "online",
          payload_not_available: "offline"
      }]
    - name: "Temperature Mock-2"
     state_topic: "home-assistant/mock-ds18b20/Mock-2"
     unit_of_measurement: "°C"
     availability: [{
          topic: "home-assistant/mock-ds18b20/availability",
          payload_available: "online",
          payload_not_available: "offline"
     }]
    - name: "Temperature Mock-3"
     state_topic: "home-assistant/mock-ds18b20/Mock-3"
     unit_of_measurement: "°C"
     availability: [{
          topic: "home-assistant/mock-ds18b20/availability",
          payload_available: "online",
          payload_not_available: "offline"
     }]